strip = neopixel.create(DigitalPin.P1, 31, NeoPixelMode.RGB)
deel1 = strip.range(0, 5)
deel2 = strip.range(5, 5)
deel3 = strip.range(10, 5)
deel4 = strip.range(15, 5)
deel5 = strip.range(20, 5)
deel6 = strip.range(25, 5)

def on_forever():
    strip.show_rainbow(1, pins.map(0, 0, 1023, 0, 4))
    basic.pause(1000)
    deel1.show_color(neopixel.colors(NeoPixelColors.BLACK))
    deel2.show_color(neopixel.colors(NeoPixelColors.WHITE))
    deel3.show_color(neopixel.colors(NeoPixelColors.BLACK))
    deel4.show_color(neopixel.colors(NeoPixelColors.WHITE))
    deel5.show_color(neopixel.colors(NeoPixelColors.BLACK))
    deel6.show_color(neopixel.colors(NeoPixelColors.WHITE))
    basic.pause(1000)
basic.forever(on_forever)
