let strip = neopixel.create(DigitalPin.P1, 31, NeoPixelMode.RGB)
let deel1 = strip.range(0, 5)
let deel2 = strip.range(5, 5)
let deel3 = strip.range(10, 5)
let deel4 = strip.range(15, 5)
let deel5 = strip.range(20, 5)
let deel6 = strip.range(25, 5)
basic.forever(function on_forever() {
    strip.showRainbow(1, pins.map(0, 0, 1023, 0, 4))
    basic.pause(1000)
    deel1.showColor(neopixel.colors(NeoPixelColors.Black))
    deel2.showColor(neopixel.colors(NeoPixelColors.White))
    deel3.showColor(neopixel.colors(NeoPixelColors.Black))
    deel4.showColor(neopixel.colors(NeoPixelColors.White))
    deel5.showColor(neopixel.colors(NeoPixelColors.Black))
    deel6.showColor(neopixel.colors(NeoPixelColors.White))
    basic.pause(1000)
})
